### ISSUE TITLE
Warning occurred when the field has not target language.

### ISSUE THREAD

**Issue by L-M-Sherlock** [kelciour/awesometts-anki-addon#17]
$1
Warning occurred when the field has no target language.
```
Unable to play this tag:
<tts service="sapi5com" quality="39" speed="0" voice="Microsoft David Desktop" volume="100" xml="16">
苹果
</tts>
Input to transcoder was 46-byte stream; wanted 4096+ bytes (the service might not have liked your input text)
```
$2
I trid to add an English word to the field, and no warning occurred. For example:
```
<tts service="sapi5com" quality="39" speed="0" voice="Microsoft David Desktop" volume="100" xml="16">
apple 苹果
</tts>
```
Seemingly AwesomeTTS ignores the chinese word in $2, but does not ignores it in $1.

**Comment by kelciour** [comment]
I think it's the correct behavior since Microsoft David Desktop - English (United States) doesn't know how to pronounce non-English text (苹果) and can only speak English.

It should work fine after installing Chinese voices (Win -> Speech settings -> Manage voices - Add voices), for example, Microsoft Huihui Desktop, and using it instead of Microsoft David Desktop to pronounce 苹果 either with AwesomeTTS or with built-in TTS in Anki 2.1.20 (https://apps.ankiweb.net/docs/manual.html#text-to-speech).

**Comment by L-M-Sherlock** [comment]
Thank you! I use Microsoft HuiHui Desktop which supports both Chinese and English.

**Comment by kelciour** [comment]
Thanks for the feedback! I thought it wasn't possible to use it with two languages at the same time, but didn't try to do it. That's great to know!
