### ISSUE TITLE
Add "Download Throttling during Batch Processing" for Microsoft Azure Text to Speech

### ISSUE THREAD

**Issue by steven31415** [kelciour/awesometts-anki-addon#52]
Microsoft Azure Text to Speech support is excellent. However when doing batch processing it returns an error after doing more than about 20 items. Can you please enable the throttling feature (sleeping a few seconds for each batch) for the Azure service?

**Comment by kelciour** [comment]
Interesting. It should be already sleeping for 30 seconds every 10 requrests. Do you have the same settings?

![изображение](https://user-images.githubusercontent.com/16260735/118574090-6dc71480-b78c-11eb-9374-29a3ec9fd137.png)

I haven't tested 20 requests and 60 seconds, but theoretically it should work too.

**Comment by steven31415** [comment]
My config looks like this:
![image](https://user-images.githubusercontent.com/3230252/118598980-c6a3a680-b7a6-11eb-9880-7e52cffbf100.png)
It seems my list of programs that use throttling is shorter, though my version is newer?

**Comment by kelciour** [comment]
The list of voices to throttle is longer because some voices doesn't work anymore and still appear in the list. They likely will be removed some time in the future from the list.

But essentially it's a different version of the AwesomeTTS add-on.

This forked repository is for this AnkiWeb version - https://ankiweb.net/shared/info/814349176 (Google Cloud Text-to-Speech)

Your screenshot must be from this version - https://ankiweb.net/shared/info/1436550454 (Add speech to your flashcards)

Any issues with it can be reported to the main repository - https://github.com/AwesomeTTS/awesometts-anki-addon/issues
