### ISSUE TITLE
The newest awesometts ignores tags

### ISSUE THREAD

**Issue by Kudorollin** [kelciour/awesometts-anki-addon#54]
Hello. I control my TTS using tags `<span class="dontread">` and in Configuration -> Text -> Advanced, I make handling text like `match <span class="dontread".*/span>`. Today, I upgraded this add-on and it ignores those tags. Can I roll back old awesome tts or do I have another option?

**Comment by kelciour** [comment]
I'm sorry about it. It was unintentional.

I'm not aware of the changes but maybe AwesomeTTS - Add speech to your flashcards - https://ankiweb.net/shared/info/1436550454 - already handles this case.

Alternatively, I'm not sure how soon the add-on will be updated, maybe weeks, but it should be fixed in the current repository. If it's still actual and you'd like to give it a go, download it as a zip, open Anki > Tools > Add-ons > AwesomeTTS > View Files, replace the awesometts subfolder and restart Anki.

**Comment by Kudorollin** [comment]
Thank you for updating. I always appreciate your devotion, so please don't be sorry. ☺

**Comment by Kudorollin** [comment]
The other version of Awesome TTS doesn't handle `<tts>` tags, instead of template tags, that means I cannot handle a variable number of speaking section in a single text. To vary the number of speaking people text by text, using `<tts>` tags is far useful.

**Comment by kelciour** [comment]
Thank you!
